services:
  mi-research-tg-bot:
    build: .
    image: mi-research-tg-bot:0.9.0
    container_name: mi-research-tg-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/app/config:ro
      - ./backups:/app/backups
      - mi-research-db:/app/database

volumes:
  mi-research-db: