"""initial_migration

Revision ID: 70542cef440d
Revises: 
Create Date: 2026-04-13 22:34:02.981850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70542cef440d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('participant_code'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('smoking_years', sa.Integer(), nullable=False),
    sa.Column('cigs_per_day', sa.Integer(), nullable=False),
    sa.Column('quit_attempts_before', sa.Boolean(), nullable=False),
    sa.Column('uses_vape', sa.Boolean(), nullable=False),
    sa.Column('smoker_in_household', sa.Boolean(), nullable=False),
    sa.Column('prior_medical_help', sa.String(), nullable=False),
    sa.Column('fagerstrom_score', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_level', sa.String(), nullable=False),
    sa.Column('fagerstrom_1', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_2', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_3', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_4', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_5', sa.Integer(), nullable=False),
    sa.Column('fagerstrom_6', sa.Integer(), nullable=False),
    sa.Column('prochaska_score', sa.Integer(), nullable=False),
    sa.Column('prochaska_level', sa.String(), nullable=False),
    sa.Column('prochaska_1', sa.Integer(), nullable=False),
    sa.Column('prochaska_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_code')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('morning_sent', sa.Boolean(), nullable=True),
    sa.Column('morning_sent_at', sa.DateTime(), nullable=True),
    sa.Column('evening_sent', sa.Boolean(), nullable=True),
    sa.Column('evening_response', sa.String(), nullable=True),
    sa.Column('evening_response_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ppa_30d', sa.Boolean(), nullable=True),
    sa.Column('ppa_7d', sa.Boolean(), nullable=True),
    sa.Column('cigs_per_day', sa.Integer(), nullable=True),
    sa.Column('quit_attempt_made', sa.Boolean(), nullable=True),
    sa.Column('days_to_first_lapse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_code')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ppa_7d', sa.Boolean(), nullable=True),
    sa.Column('cigs_per_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('smoking_status', sa.String(), nullable=True),
    sa.Column('craving_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('craving_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('sos_usage_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('trigger_situation', sa.Text(), nullable=True),
    sa.Column('thoughts', sa.Text(), nullable=True),
    sa.Column('physical_sensation', sa.Text(), nullable=True),
    sa.Column('coping_strategy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.ForeignKeyConstraint(['sos_usage_id'], ['sos_usage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('craving_analyses')
    op.drop_table('weekly_checkins')
    op.drop_table('sos_usage')
    op.drop_table('follow_ups')
    op.drop_table('final_surveys')
    op.drop_table('daily_logs')
    op.drop_table('baseline_questionnaires')
    op.drop_table('techniques')
    op.drop_table('participants')
    # ### end Alembic commands ###
