"""initial migration

Revision ID: a56ea5545eaf
Revises: 
Create Date: 2026-04-12 18:01:21.855033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56ea5545eaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('registration_date', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('fagerstrom_score', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_level', sa.String(), nullable=True),
    sa.Column('prochaska_score', sa.Integer(), nullable=True),
    sa.Column('prochaska_level', sa.String(), nullable=True),
    sa.Column('fagerstrom_1', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_2', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_3', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_4', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_5', sa.Integer(), nullable=True),
    sa.Column('fagerstrom_6', sa.Integer(), nullable=True),
    sa.Column('prochaska_1', sa.Integer(), nullable=True),
    sa.Column('prochaska_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('participant_code'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('techniques')
    op.drop_table('participants')
    # ### end Alembic commands ###
